version: "2.3"

services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dmsp-dynamodb-local
    ports:
      - "8001:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  mysql:
    restart: always
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    image: mysql/mysql-server:latest
    container_name: dmsp-mysql-local
    ports:
      - "3307:3306"
    expose:
      - "3307"
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - "./docker/mysql:/var/lib/mysql"

  app:
    depends_on:
      - mysql
      - dynamodb-local
    build: .
    command: "bundle exec rails server -p 3000 -b '0.0.0.0'"
    volumes:
      - ".:/app"
    ports:
      - "3001:3000"
    expose:
      - "3001"
    links:
      - mysql
      - "dynamodb-local"
    environment:
      RAILS_ENV: "docker"
      DB_HOST: mysql
      DB_PORT: "3306"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
    env_file:
      - '.env'

    # TODO: Monitor the compose watch project. It currently is not allowing sync. There is an open discussion
    #       here: https://github.com/docker/compose/issues/11102
    develop:
      watch:
        # Watch the files in the app/ dir and update the container when they change
        - action: sync
          path: ./app
          target: /rails/app

        # Rebuild the container if any changes are made to these locations
        - action: rebuild
          path: ./bin
        - action: rebuild
          path: ./config
        - action: rebuild
          path: Gemfile.lock
